//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendanceSystem.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceId { get; set; }
        public int PersonnelId { get; set; }
        public Nullable<double> SickLeave { get; set; }
        public Nullable<double> CumulativeSickLeave { get; set; }
        public Nullable<double> PrivateLeave { get; set; }
        public Nullable<double> CumulativePrivateLeave { get; set; }
        public Nullable<double> TransformLeave { get; set; }
        public Nullable<int> OtherLeaveTypeId { get; set; }
        public Nullable<int> LateTime { get; set; }
        public Nullable<int> Absenteeism { get; set; }
        public Nullable<double> AttendanceHour { get; set; }
        public Nullable<double> OvertimeHour { get; set; }
        public string Note { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual LeaveType LeaveType { get; set; }
        public virtual Personnel Personnel { get; set; }
    }
}
